<?php $developerPath = parse_url($_SERVER['REQUEST_URI'] ?? '/developer', PHP_URL_PATH) ?: '/developer'; ?>
<aside class="developer-sidebar">
<div class="developer-brand"><?php $brandClass = 'brand developer-brand-link'; $brandHref = '/developer'; require __DIR__ . '/../components/brand.php'; ?><small>Content Studio</small></div>
<button class="mobile-menu-button developer-menu-button" type="button" aria-expanded="false" aria-controls="developer-nav"><span class="sr-only">Toggle developer navigation</span><?php $icon = 'menu'; require __DIR__ . '/../components/icon.php'; ?></button>
<nav id="developer-nav" aria-label="Developer navigation">
<h3>Overview</h3><a href="/developer"<?= $developerPath === '/developer' ? ' aria-current="page"' : '' ?>><?php $icon = 'home'; require __DIR__ . '/../components/icon.php'; ?>Dashboard</a>
<h3>Content</h3><a href="/question-editor"<?= $developerPath === '/question-editor' ? ' aria-current="page"' : '' ?>><?php $icon = 'question'; require __DIR__ . '/../components/icon.php'; ?>Questions</a><a href="/question-editor/create"><?php $icon = 'edit'; require __DIR__ . '/../components/icon.php'; ?>Create Question</a><a href="/question-import"><?php $icon = 'arrow'; require __DIR__ . '/../components/icon.php'; ?>Import</a><a href="/developer/study-library"<?= $developerPath === '/developer/study-library' ? ' aria-current="page"' : '' ?>><?php $icon = 'book'; require __DIR__ . '/../components/icon.php'; ?>Study Library</a>
<h3>Structure</h3><a href="/boards"><?php $icon = 'exam'; require __DIR__ . '/../components/icon.php'; ?>Boards</a><a href="/subjects"><?php $icon = 'book'; require __DIR__ . '/../components/icon.php'; ?>Subjects</a><a href="/taxonomy"><?php $icon = 'topic'; require __DIR__ . '/../components/icon.php'; ?>Taxonomy</a><a href="/blueprints"><?php $icon = 'target'; require __DIR__ . '/../components/icon.php'; ?>Blueprints</a>
<h3>Quality</h3><a href="/question-inspector"><?php $icon = 'inspect'; require __DIR__ . '/../components/icon.php'; ?>Inspector</a><a href="/question-quality"><?php $icon = 'check'; require __DIR__ . '/../components/icon.php'; ?>Quality</a><a href="/coverage"><?php $icon = 'chart'; require __DIR__ . '/../components/icon.php'; ?>Coverage</a><a href="/metadata-repair"><?php $icon = 'settings'; require __DIR__ . '/../components/icon.php'; ?>Metadata repair</a>
<h3>System</h3><a href="/developer/doctor"><?php $icon = 'doctor'; require __DIR__ . '/../components/icon.php'; ?>Doctor</a><a href="/"><?php $icon = 'arrow'; require __DIR__ . '/../components/icon.php'; ?>View site</a>
</nav></aside>
